#! /usr/bin/env bash

first_name="${BASH_SOURCE[0]}"
actual_name="$(readlink -f "${first_name}")"
local_path="$(dirname "${actual_name}")"

. "${local_path}/logging"

modules::install::git() {
    local _url="${1?Need to provide a GIT url}"
    local _branch="${2:-master}"
    local _tempdir
    local _result=true

    if _tempdir="$(mktemp --directory --quiet)"
    then
        if ! git clone "${_url}" "${_tempdir}" --branch="${_branch}"
        then
            logging::error "Failed to extract from repo '${_url}'"
            _result=false
        elif ! pushd "${_tempdir}" >/dev/null 2>&1
        then
            logging::error "Couldn't use temporary folder '${_tempdir}'"
            _result=false
        else
            if [ -f Makefile ]
            then
                if ! make install
                then
                    logging::error "Failed running make on '${_url}'"
                    _result=false
                fi
            elif [ -f setup.py ]
            then
                if ! "$(virtualenv::python)" setup.py install
                then
                    logging::error "Couldn't install python package from '${_url}'"
                    _result=false
                fi
            fi

            popd
        fi

        if ! ${_result}
        then
            logging::info "Successfully installed branch '${_branch}' from package '${_url}'"
        fi

        rm -rf "${_tempdir}"
    fi

    "${_result}"
}
