#! /usr/bin/env bash

export BASHLIB_VERSION=0.01

first_name="${BASH_SOURCE[0]}"
actual_name="$(readlink -f "${first_name}")"
local_path="$(dirname "${actual_name}")"
lib_path="${local_path}/bashLib-${BASHLIB_VERSION}"

. "${lib_path}/logging"
. "${lib_path}/functional"
. "${lib_path}/exceptions"
. "${lib_path}/containers"
. "${lib_path}/environments"
