#! /usr/bin/env bash

package_name=bashLib
first_name="${BASH_SOURCE[0]}"
actual_name="$(readlink -f "${first_name}")"
local_path="$(dirname "${actual_name}")"

export BASHLIB_VERSION="$(
    find "${local_path}/${package_name}"-[.0-9]* -maxdepth 0 -mindepth 0 -type d -printf "%f\n" |
    awk -F- '{print $NF;}' |
    sort -nr |
    head -1
)"

lib_path="${local_path}/${package_name}-${BASHLIB_VERSION}"

. "${lib_path}/logging"
. "${lib_path}/tabular"
. "${lib_path}/exceptions"
. "${lib_path}/containers"
. "${lib_path}/arguments"
. "${lib_path}/virtualenv"
. "${lib_path}/modules"
. "${lib_path}/url"

bashlib::version() {
    echo "${BASHLIB_VERSION}"
}

hash -r
