#! /usr/bin/env bash

package_name=bashLib
first_name="${BASH_SOURCE[0]}"
actual_name="$(readlink -f "${first_name}")"
local_path="$(dirname "${actual_name}")"

export BASHLIB_VERSION="$(
    find "${local_path}/${package_name}"-[.0-9]* -maxdepth 0 -mindepth 0 -type d -printf "%f\n" |
    awk -F- '{print $NF;}' |
    sort -nr |
    head -1
)"

lib_path="${local_path}/${package_name}-${BASHLIB_VERSION}"

export BASHLIB_SUBCOMMANDS_PATH="${lib_path}/subcommands"

. "${lib_path}/logging"
. "${lib_path}/tabular"
. "${lib_path}/exceptions"
. "${lib_path}/container_instances"
. "${lib_path}/container_groups"
. "${lib_path}/process"
. "${lib_path}/arguments"
. "${lib_path}/virtualenv"
. "${lib_path}/modules"
. "${lib_path}/network"
. "${lib_path}/list"
. "${lib_path}/url"
. "${lib_path}/properties"
. "${lib_path}/option_parsing"
. "${lib_path}/settings"

bashlib::version() {
    echo "${BASHLIB_VERSION}"
}

bashlib::subcommands::path() {
    echo "${BASHLIB_SUBCOMMANDS_PATH}"
}

bashlib::subcommands() {
    find "$(bashlib::subcommands::path)" -type f -printf "%f\n" 2>/dev/null
}

hash -r
