#! /usr/bin/env bash

first_name="${BASH_SOURCE[0]}"
actual_name="$(readlink -f "${first_name}")"
local_path="$(dirname "${actual_name}")"

. "${local_path}/logging"

docker::image() {
    local _image="${1:?Provide a container image}"

    if (sudo -A docker images "${_image}" | grep -q "${_image}")
    then
        true
    else
        logging::warning "Importing image ${_image}"
        sudo -A docker pull "${_image}"
    fi
}

docker::instance() {
    local _collection="${1:?Provide a collection name}"
    local _image="${2:?Provide a container image}"
}

