#! /usr/bin/env bash

first_name="${BASH_SOURCE[0]}"
actual_name="$(readlink -f "${first_name}")"
local_path="$(dirname "${actual_name}")"

. "${local_path}/logging"

modules::install::git() {
    local _url="${1?Need to provide a GIT url}"
    local _tempdir

    if _tempdir="$(mktemp --directory --quiet)"
    then
        if ! git clone "${_url}" "${_tempdir}" --branch=master
        then
            logging::error "Failed to extract from repo '${_url}'"
        elif ! cd "${_tempdir}"
        then
            logging::error "Couldn't select path '${_tempdir}'"
        elif ! make install
        then
            logging::error "Couldn't install package from '${_url}'"
        fi

        rm -rf "${_tempdir}"
    fi
}
