#! /usr/bin/env bash

first_name="${BASH_SOURCE[0]}"
actual_name="$(readlink -f "${first_name}")"
local_path="$(dirname "${actual_name}")"

. "${local_path}/logging"

virtualenv::path() {
    python -c 'import sys; print "" if not hasattr(sys, "real_prefix") else sys.prefix'
}

virtualenv::create() {
    local _env="${1:?Provide a virtualenv path}"
    
    if [ -d "${_env}" ]
    then
        logging::warning "Using existing virtual environment in '${_env}'"
    elif python -m venv --system-site-packages "${_env}" 2>/dev/null
    then
        logging::warning "Created virtual environment in '${_env}'"
    elif virtualenv "${_env}" --system-site-packages 2>/dev/null
    then
        logging::warning "Created virtual environment in '${_env}'"
    else
        logging::fatal "Cannot create virtualenv in '${_env}'"
    fi
}
