#! /usr/bin/env bash

first_name="${BASH_SOURCE[0]}"
actual_name="$(readlink -f "${first_name}")"
local_path="$(dirname "${actual_name}")"

. "${local_path}/arguments"
. "${local_path}/logging"

tabular::separator() {
    if [ -n "${1}" ]
    then
        export __BASHLIB__SEPARATOR__="${1}"
        return
    elif [ -z "${__BASHLIB__SEPARATOR__}" ]
    then
        export __BASHLIB__SEPARATOR__="|||"
    fi

    echo "${__BASHLIB__SEPARATOR__}"
}

#==========================================================================
# Apply a named function or command string  over a column headed, tabular
# input stream. The column headers will be used to create shell variables
# named _column_<name> containing that column's contents, inside the function
# as it is executed per row
#
# Example:
#       (echo One; echo 1; echo 2) | tabular::apply 'echo ${_column_one}'
#
# Params:
#        function_name or shell command string
#        column separator (defaults to tabular::separator())
#==========================================================================
tabular::apply() {
    local _fn="${1:?Provide a function name or command string}"
    local _regex="$(echo "${2:-$(tabular::separator)}" | sed -e 's/./\[\\&\]/g')"
    local _prefix="_column_"
    local _columns
    local _meta_row
    local _myfunction

    shift

    if ! declare -F "${_fn}" >/dev/null 2>&1
    then
        eval "_myfunction() { "${_fn}"; }" && _fn=_myfunction
    fi

    if read _columns
    then
        local _meta_rownumber=0

        local _meta_columns="$(
            echo "${_columns}" |
            tr '[A-Z]' '[a-z]' |
            sed -e 's/'"${_regex}"'/\n/g' |
            sed -e '/^[ ]*$/d' |
            sed -e 's/[ ][ ]*/_/g' -e 's/[\W]*//g'
        )"

        local _remapper="$(
            echo "${_meta_columns}" | {
                _pos_regex='^'
                _nl=

                while read _column
                do
                    echo "s/${_pos_regex}/${_nl}${_column}=/1"
                    _pos_regex="${_regex}"
                    _nl="\\n"
                done

                echo "s/${_pos_regex}.*$//g"
            }
        )"

        while read _meta_row
        do
            eval "$(
                echo "${_meta_row}" |
                sed "${_remapper}" |
                sed -e 's/[\=]\(.*\)$/=\"\1\"/g' -e 's/^/local '"${_prefix}"'/1'
            )"

            "${_fn}" $@ || break

            ((++_meta_rownumber))
        done
    fi
}

tabular::filter() {
    local _fn="${1:?Provide a function name or command string}"
    local _sep="${2:-$(tabular::separator)}"
    local _cmd="${_fn}"' && echo "${_meta_row}"; true'
    local _header

    read _header
    echo "${_header}"
    (echo "${_header}"; cat) | tabular::apply "${_cmd}" "${_sep}"
}

tabular::where() {
    # Convenience wrapper for filter, takes a bare comparison expression
    # for one of the apply column names
    # Example
    # (echo one,two; echo 1,2; echo 4,5) | tabular::where 'one == 1' ,

    local _clause="(( _column_"${1:?Need to provide a clause}" ))"
    local _sep="${2:-$(tabular::separator)}"

    tabular::filter "${_clause}" ${_sep}
}

tabular::transpose() {
    # Turn single value column into row wise data
    awk '{printf("%s%s", sep, $0); sep=separator;} END {printf("\n");}' separator="${1:-$(tabular::separator)}"
}

tabular::merge() {
    # Merge multiple files row by row (will force rectilinear)

    eval "$(arguments::formatter "$@")"

    local _offset=${kwargs["offset"]:-10}
    local _sep="${kwargs["separator"]:-$(tabular::separator)}"
    local _count=${_offset:-0}
    local _filename

    for _filename in "${args[@]}"
    do
        eval exec "${_count}<${_filename}"
        ((++_count))
    done

    local -a _values=()
    local _row
    local _fd
    local _col
    local _s

    test "${_count}" -gt "${_offset}" && while true
    do
        _values=()

        for ((_fd=${_offset}; _fd < ${_count}; ++_fd)) {
            eval read _row "<&${_fd}" || return 255
            _values[${#_values[@]}]="${_row}"
        }

        _s=

        for ((_col=0; _col < ${#_values[@]}; ++_col)) {
            echo -n "${_s}${_values[${_col}]}"
            _s="${_sep}"
        }
        echo
    done
}
