#! /usr/bin/env bash

first_name="${BASH_SOURCE[0]}"
actual_name="$(readlink -f "${first_name}")"
local_path="$(dirname "${actual_name}")"

. "${local_path}/logging"
. "${local_path}/arguments"

export BASHLIB_NETWORK_REGISTRY="${BASHLIB_NETWORK_REGISTRY:-/var/tmp/${USER}/network-service-ports.csv}"

network::services() {
    network::services::list
}

network::services::registry() {
    if [ -n "${1}" ]
    then
        export BASHLIB_NETWORK_REGISTRY="${1}"
    elif [ -z "${BASHLIB_NETWORK_REGISTRY}" ]
    then
        logging::error "No network registry has been chosen"
        return 255
    else
        echo "${BASHLIB_NETWORK_REGISTRY}"
    fi
}

network::services::list() {
    local _registry=

    if ! _registry="$(network::services::registry)"
    then
        return 255
    fi

    local _folder="$(dirname "${_registry}")"

    if [ -z "${_folder}" ]
    then
        logging::error "Invalid folder '${_folder}'"
        return 255
    elif [ -d "${_folder}" ] || mkdir -p "${_folder}" ]
    then
        :
    else
        logging::error "Cannot access folder '${_folder}'"
        return 255
    fi

    if [ ! -f "${_registry}" 
    cat
}
