#! /usr/bin/env bash

. $(bashlibtool --lib)

group_definition() {
    sed -e 's/^        //g' <<'    EOF' | m4 -DGROUP_NAME="TestGroup" -DIMAGE="ubuntu"
    {
            "groups": {
                "GROUP_NAME": [
                    {
                        "name": "One",
                        "image": "IMAGE",
                        "install": "",
                        "startup": ""
                    },
                    {
                        "name": "Two",
                        "image": "IMAGE",
                        "install": "",
                        "startup": ""
                    }
                ]
            }
        }
    EOF
}

docker::start_group "$(group_definition)"

