#! /usr/bin/env bash

first_name="${BASH_SOURCE[0]}"
actual_name="$(readlink -f "${first_name}")"
local_path="$(dirname "${actual_name}")"

. "${local_path}/logging"

environments::virtualenv_path() {
    python -c 'import sys; print "" if not hasattr(sys, "real_prefix") else sys.prefix'
}