#! /usr/bin/env bash

first_name="${BASH_SOURCE[0]}"
actual_name="$(readlink -f "${first_name}")"
local_path="$(dirname "${actual_name}")"

tools::columnize() {
    echo "${@}" | awk '{printf("%s%s", sep, $0); sep="|";} END {printf("\n");}'
}