#!/usr/bin/env bash

#===================================================================================
#                          Import tools library
#===================================================================================
. "$(bashlib --lib)"

#===================================================================================
#                              Logging Options
#===================================================================================
logging::set_severity info

#===================================================================================
#                              Help Message
#===================================================================================
showhelp() {
    local _synopsis="
        Maintain running containers
    "

    local -A _keywords=(
        [debug]="Expose debug level logging"
        [info]="Expose normal level logging"
        [warning]="Expose error level logging"
        [error]="Expose error level logging"
        [fatal]="Expose fatal error level logging"
        [status]="List container states"
        [start]="Start a container"
        [stop]="Stop a container"
        [rebuild]="Rebuild a container"
        [cleanup]="Delete a container"
        [instance:]="Specify a container instance"
        [image:]="Specify an image name"
        [commit]="Save a container instance as an image"
        [tag:]="Specify an image tag (default: latest)"
        [version]="Produce the version string"
        [help]="Display instructions"
    )

    local _terms="$(echo "${@}" | awk -F, '{for (i=1; i <= NF; ++i) {print $i;}}')"
    local _topic

    local _contents="$(
        echo "${_terms}" | awk -F: '{printf("%s[--%s%s]", sep, $1, (NF == 2 ? sprintf("=<%s>", $1) : "")); sep=" "}'
        echo -en "${_synopsis:+\n\n}"
        echo "${_synopsis}" | sed -e 's/^[ ]*//g' -e '/^[ ]*$/d'

        echo "${_terms}" | {
            _prefix="\n"

            while read _topic
            do
                if [ -n "${_keywords["${_topic}"]}" ]
                then
                    _fill="$(for ((i=$(echo -n "${_topic}" | wc -c); i < 15; ++i)); do echo -n " "; done)"
                    echo -e "${_prefix}--${_topic}${_fill}${_keywords["${_topic}"]}" | sed -e 's/^./    &/g'
                    _prefix=""
                fi
            done
        }
    )"

    echo -e "Usage: $0 ${_contents}\n" >&2
}

#===================================================================================
# NOTE: There is a bug in getopts where not specifying at least one short option
#       will cause the first non option parameter to be discarded. Here, we just
#       use -h (help)
#===================================================================================
long_options="help,version,debug,info,warning,error,fatal,start,stop,rebuild,cleanup,status,instance:,name:,image:,tag:,console,commit"

OPTION_TEMP=$(getopt -a -o hv --long ${long_options} -- "$@")

if [ $? != 0 ]
then
    logging::fatal "Invalid command line options ${OPTION_TEMP}"
fi

eval set -- "$OPTION_TEMP"

#===================================================================================
#                       Process command line parameters
#
# NOTE: The command line parameters are available for scripts which
#       source this file.
#===================================================================================
action=
image=
tag=
instance_name=

while true
do
    case "$1" in
        --debug|--info|--warning|--error|--fatal)
            logging::set_severity "$(echo "${1}" | sed -e 's/^[\-]*//g')"
            shift
            ;;

        --start|--stop|--rebuild|--cleanup|--status|--console|--commit)
            action="$(echo "${1}" | sed -e 's/^[-]*//g')"
            shift
            ;;

        --image)
            image="$2"
            shift 2
            ;;

        --instance|--name)
            instance_name="$2"
            shift 2
            ;;

        --tag)
            tag="$2"
            shift 2
            ;;

        --version)
            bashlib::version
            exit 0
            ;;

        --)
            shift
            break
            ;;

        *)
            showhelp "${long_options}" >&2
            exit 0
            ;;
    esac
done

#===================================================================================
#                             Perform selected action
#===================================================================================
case "${action}" in
    commit)
        container::instance::save_image instance="${instance_name}" image="${image}" tag="${tag}"
        exit $?
        ;;

    start)
        container::instance::start instance="${instance_name}" image="${image}" tag="${tag}"
        exit $?
        ;;

    rebuild)
        container::instance::rebuild instance="${instance_name}" image="${image}" tag="${tag}"
        exit $?
        ;;

    status)
        container::instance::instances instance="${instance_name}"
        exit $?
        ;;

    cleanup)
        container::instance::cleanup instance="${instance_name}"
        exit $?
        ;;

    stop)
        container::instance::stop instance="${instance_name}"
        exit $?
        ;;

    console)
        container::instance::console instance="${instance_name}"
        exit $?
        ;;

    *)
        logging::fatal "Unknown or invalid action '${action}'"
        ;;
esac