#! /usr/bin/env bash

first_name="${BASH_SOURCE[0]}"
actual_name="$(readlink -f "${first_name}")"
local_path="$(dirname "${actual_name}")"

. "${local_path}/logging"

exceptions::_base() {
    logging::fatal "$@"
    exit 255
}

exceptions::Unimplemented() {
    exceptions::_base "Unimplemented"
}

