#! /usr/bin/env bash

first_name="${BASH_SOURCE[0]}"
actual_name="$(readlink -f "${first_name}")"
local_path="$(dirname "${actual_name}")"
library_import_file="$(readlink -f "${local_path}/../lib/bashLib")"

#===================================================================================
#                          Import tools library
#===================================================================================
. "${library_import_file}"

#===================================================================================
#                              Logging Options
#===================================================================================
logging::set_severity info

#===================================================================================
#                              Help Message
#===================================================================================
showhelp()
{
    contents=$(
        echo "${*}" |
        awk -F, '{for (i=1; i <= NF; ++i) {print $i;}}' |
        awk -F: '{printf("%s[--%s%s]", sep, $1, (NF == 2 ? sprintf("=<%s>", $1) : "")); sep=" "}'
    )

    echo "Usage: $0 ${contents}" >&2
}

#===================================================================================
# NOTE: There is a bug in getopts where not specifying at least one short option
#       will cause the first non option parameter to be discarded. Here, we just
#       use -h (help)
#===================================================================================
long_options="help,version,debug,info,warning,fatal,env::,lib,virtualenv::"

OPTION_TEMP=$(getopt -a -o hv --long ${long_options} -- "$@")

if [ $? != 0 ]
then
    logging::fatal "Invalid command line options ${OPTION_TEMP}"
fi

eval set -- "$OPTION_TEMP"

#===================================================================================
#                       Process command line parameters
#
# NOTE: The command line parameters are available for scripts which
#       source this file.
#===================================================================================
while true
do
    case "$1" in
        --debug|--info|--warning|--fatal)
            logging::set_severity "$(echo "${1}" | sed -e 's/^[\-]*//g')"
            shift
            ;;

        --env|--virtualenv)
            shift 2

            if [ "${2}" = "" ]
            then
                environments::virtualenv_path
                exit 0
            fi

            if ! . "${2}/bin/activate"
            then
                logging::fatal "Cannot select virtual environment in '${2}'"
            fi
            ;;

        --lib)
            echo "${library_import_file}"
            shift
            exit 0
            ;;

        --version)
            echo "${BASHLIB_VERSION}"
            exit 0
            ;;

        --)
            shift
            break
            ;;

        *)
            showhelp "${long_options}" >&2
            exit 0
            ;;
    esac
done

#===================================================================================
#                                Handle requests
#===================================================================================
for command in $@
do
    case "${command}" in
        *)
            logging::fatal "Unknown command ${command}"
            ;;
    esac
done
